language: php
php:
- 5.5
- 5.6
- hhvm
matrix:
  allow_failures:
  - php: hhvm
before_script:
- composer install --no-interaction
script:
- vendor/bin/phpunit --verbose --coverage-text
notifications:
  slack:
    secure: jVmHh5vAE3oAr8ga2Jn0QAbWRoQUbtx9XjunZqJyxJStA1lHmdLasc/dKfb1S+v6IxZjmpmT8Q1BLLmg9WkT99fQNvwA3eUMqy+11AEPP6q1qTNlcQsfC2hU/twD6ZyQ6IevM5i+eOTB4LzBqBpbZSCZcJ8IK6c6s1QrCEDdSflezDAWKC5C7Z19/T+RWAwmXKRCOUwotQRqCNflTZjQY+7cexOUPDTq4mPdwF3dMwTJy9Vq5pm6d367mjydDNpiFbwyS79exLkLlszgfOmNzRGxC3KJfP/SOTKT8tPazpYnbMWX/TRbNA9hhMQwrgDhQduuVPrkR88nGSJlU7AtrnaskPdAVZa16+p7DU51Ejd2SqQ/fJM2XpiAf9j/JivYrgooYAzLUgpWJd/7L52yEzmFJbGyroPNi/sy+8KzLF3BAqenwTaYdZ99Ur7YekvKlVXjr33hMX2MZGG5waU2nF91/v64llI/47CMBMjQNIJyaao5E5Ap/us9LPSwDg9oe+Ed5pUAY62JqGNFJq/EA/V9hKRWo6KPbLd9ieE77OrW+islR2wROf6s8zdzrvGCi3d4W1keXYsKoe1V/hW43G0CHuQhHrclc5XLdsvY1hUgZkavnIGgTC2mDomlrH5unfw8OkF8PmcC3FElywKjHtNisawlAx7hO45NqMDM3jc=
